name: UltimateDuping
version: '1.0.2'
main: dev.rishon.ultimateduping.UltimateDuping
api-version: 1.19
authors: [ Rishon ]
description: Minecraft 1.19.2 Duping Plugin
website: https://rishon.systems
commands:
  dupe:
    description: Main dupe command to open Dupe GUI.
